LLAVA_IGNORE_INDEX=-100
LLAVA_DEFAULT_IMAGE_TOKEN = "<image>" # 32000
LLAVA_DEFAULT_IM_START_TOKEN = "<s>"
LLAVA_DEFAULT_IM_END_TOKEN = "</s>"
LLAVA_STOP_INDEX = 2 # </s>
LLAVA_PROPRIO_PAD_IDX = 32002
LLAVA_ACTION_TOKEN_BEGIN_IDX = 32002 
LLAVA_DEFAULT_IMAGE_TOKEN_IDX = 32000

BITNET_IGNORE_INDEX = -100
BITNET_DEFAULT_IM_START_TOKEN = '<|begin_of_text|>'
BITNET_DEFAULT_IM_END_TOKEN = '<|end_of_text|>'
BITNET_DEFAULT_IMAGE_TOKEN = '<|image_pad|>'
BITNET_STOP_INDEX = 128001 # '<|end_of_text|>'
BITNET_DEFAULT_IMAGE_TOKEN_IDX = 128010
BITNET_PROPRIO_PAD_IDX = 128011
BITNET_ACTION_TOKEN_BEGIN_IDX = 128011 